ALTER TABLE PERSON
DROP
FOREIGN KEY FK_hfjruvja5peldg0o5hw7g0v51;

ALTER TABLE PERSON_TO_SCAN
DROP
FOREIGN KEY FK_fb6h2mj5tgng0lfw4qjisat0f;

ALTER TABLE PERSON_TO_SCAN
DROP
FOREIGN KEY FK_1vqhihu34kpwlo0ppe82ja3on;

ALTER TABLE ROLE_TO_PERMISSION
DROP
FOREIGN KEY FK_rnherxb8242khbxdi27y022bb;

ALTER TABLE ROLE_TO_PERMISSION
DROP
FOREIGN KEY FK_lwwdu62jxvubui4annsb8uda6;

ALTER TABLE SCANNER_TASK
DROP
FOREIGN KEY FK_sb7ekumnbj0ee1wkkkaokuynp;

ALTER TABLE USER_TO_ROLES
DROP
FOREIGN KEY FK_ln9ev0ylplcc4mqjadqr0keoy;

ALTER TABLE USER_TO_ROLES
DROP
FOREIGN KEY FK_28ugs9imwewn8426ppkiq7amu;

DROP TABLE IF EXISTS PERSON;

DROP TABLE IF EXISTS PERSON_TO_SCAN;

DROP TABLE IF EXISTS ROLE_TO_PERMISSION;

DROP TABLE IF EXISTS SCAN;

DROP TABLE IF EXISTS SCANNER_TASK;

DROP TABLE IF EXISTS SEC_PERMISSION;

DROP TABLE IF EXISTS SEC_ROLE;

DROP TABLE IF EXISTS SEC_USER;

DROP TABLE IF EXISTS USER_TO_ROLES;

CREATE TABLE PERSON (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME,
  CREATED_BY  VARCHAR(60),
  DELETE_DATE DATETIME,
  DELETED_BY  VARCHAR(60),
  UPDATE_DATE DATETIME,
  UPDATED_BY  VARCHAR(60),
  VERSION     INTEGER,
  FIRSTNAME   VARCHAR(255),
  LASTNAME    VARCHAR(255),
  MIDDLENAME  VARCHAR(255),
  USER_ID     BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE PERSON_TO_SCAN (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME,
  CREATED_BY  VARCHAR(60),
  DELETE_DATE DATETIME,
  DELETED_BY  VARCHAR(60),
  UPDATE_DATE DATETIME,
  UPDATED_BY  VARCHAR(60),
  VERSION     INTEGER,
  PERSON_ID   BIGINT,
  SCAN_ID     BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE_TO_PERMISSION (
  PERMISSION_ID BIGINT NOT NULL,
  ROLE_ID       BIGINT NOT NULL
);

CREATE TABLE SCAN (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME,
  CREATED_BY  VARCHAR(60),
  DELETE_DATE DATETIME,
  DELETED_BY  VARCHAR(60),
  UPDATE_DATE DATETIME,
  UPDATED_BY  VARCHAR(60),
  VERSION     INTEGER,
  SCAN_ID     BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE SCANNER_TASK (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME,
  CREATED_BY  VARCHAR(60),
  DELETE_DATE DATETIME,
  DELETED_BY  VARCHAR(60),
  UPDATE_DATE DATETIME,
  UPDATED_BY  VARCHAR(60),
  VERSION     INTEGER,
  REASON      VARCHAR(255),
  RESULT      INTEGER,
  PERSON_ID   BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE SEC_PERMISSION (
  ID                BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE       DATETIME,
  CREATED_BY        VARCHAR(60),
  DELETE_DATE       DATETIME,
  DELETED_BY        VARCHAR(60),
  UPDATE_DATE       DATETIME,
  UPDATED_BY        VARCHAR(60),
  VERSION           INTEGER,
  ACCESS            BOOLEAN,
  PERMISSION_OBJECT VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE SEC_ROLE (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME,
  CREATED_BY  VARCHAR(60),
  DELETE_DATE DATETIME,
  DELETED_BY  VARCHAR(60),
  UPDATE_DATE DATETIME,
  UPDATED_BY  VARCHAR(60),
  VERSION     INTEGER,
  DESCRIPTION LONGTEXT,
  NAME        VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE SEC_USER (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME,
  CREATED_BY  VARCHAR(60),
  DELETE_DATE DATETIME,
  DELETED_BY  VARCHAR(60),
  UPDATE_DATE DATETIME,
  UPDATED_BY  VARCHAR(60),
  VERSION     INTEGER,
  PASSWORD    VARCHAR(255),
  USERNAME    VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE USER_TO_ROLES (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL
);

ALTER TABLE PERSON
ADD INDEX FK_hfjruvja5peldg0o5hw7g0v51 (USER_ID),
ADD CONSTRAINT FK_hfjruvja5peldg0o5hw7g0v51
FOREIGN KEY (USER_ID)
REFERENCES SEC_USER (ID);

ALTER TABLE PERSON_TO_SCAN
ADD INDEX FK_fb6h2mj5tgng0lfw4qjisat0f (PERSON_ID),
ADD CONSTRAINT FK_fb6h2mj5tgng0lfw4qjisat0f
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID);

ALTER TABLE PERSON_TO_SCAN
ADD INDEX FK_1vqhihu34kpwlo0ppe82ja3on (SCAN_ID),
ADD CONSTRAINT FK_1vqhihu34kpwlo0ppe82ja3on
FOREIGN KEY (SCAN_ID)
REFERENCES SCAN (ID);

ALTER TABLE ROLE_TO_PERMISSION
ADD INDEX FK_rnherxb8242khbxdi27y022bb (ROLE_ID),
ADD CONSTRAINT FK_rnherxb8242khbxdi27y022bb
FOREIGN KEY (ROLE_ID)
REFERENCES SEC_ROLE (ID);

ALTER TABLE ROLE_TO_PERMISSION
ADD INDEX FK_lwwdu62jxvubui4annsb8uda6 (PERMISSION_ID),
ADD CONSTRAINT FK_lwwdu62jxvubui4annsb8uda6
FOREIGN KEY (PERMISSION_ID)
REFERENCES SEC_PERMISSION (ID);

ALTER TABLE SCANNER_TASK
ADD INDEX FK_sb7ekumnbj0ee1wkkkaokuynp (PERSON_ID),
ADD CONSTRAINT FK_sb7ekumnbj0ee1wkkkaokuynp
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID);

ALTER TABLE SEC_USER
ADD CONSTRAINT UK_46psvtdbgrirs6s7ib5d3hs49 UNIQUE (USERNAME);

ALTER TABLE USER_TO_ROLES
ADD INDEX FK_ln9ev0ylplcc4mqjadqr0keoy (ROLE_ID),
ADD CONSTRAINT FK_ln9ev0ylplcc4mqjadqr0keoy
FOREIGN KEY (ROLE_ID)
REFERENCES SEC_ROLE (ID);

ALTER TABLE USER_TO_ROLES
ADD INDEX FK_28ugs9imwewn8426ppkiq7amu (USER_ID),
ADD CONSTRAINT FK_28ugs9imwewn8426ppkiq7amu
FOREIGN KEY (USER_ID)
REFERENCES SEC_USER (ID);
